
#=============================================================================================#
#                                      STATIC GlOBALS                                         #
#=============================================================================================#

# directory path globals
DATA_INPUT_DIR = 'data_inputs'
DATA_OUTPUT_DIR = 'data_outputs'
LIB_DIR = 'lib'
PIPELINE_DIR = 'pipelines'
SAVED_GENS_DIR = 'saved_generations'

JSON_DIR = 'json_lib'
STATIC_JSON_LIB = 'static_json_lib'


# boilerplate file code
PIPELINE_BOILERPLATE = '''
# generated_pipeline.py

# This file is intended to be a reusable data pipeline.

import pandas as pd

from lib.static_lib import *
from lib.pipeline_lib import *

'''

PIPELINE_LIB_BOILERPLATE = '''
# pipeline_lib.py

'''


#=============================================================================================#
#                                      PROMPT GlOBALS                                         #
#=============================================================================================#

# Task List
# Jesse 1/20/25 - 
#       1.) We need the "TASK: what the task is" to be dyanmically generated by a task creation agent.

TASKS = [
    (
        "TASK: Fix any spelling errors that exist in the rows of the df.\n" 
    ),
    (
        "TASK: Remove any duplicates from the df.\n"
    )
]
# Instructions on how to proceed through each task.
TASK_INST = (
    "Use the steps below to complete the task.\n"
    "1.) Use the search_lib tool to find an appropriate function for the task.\n"
    "2.) Use the execute_existing_code tool to complete the task on the df.\n"
    "3.) If, and only if, no appropriate function is found to complete the task, proceed as follows: "
    "   a) Use the coding_instructions tool to view guidelines for writing the function.\n"
    "   b) Use the write_generated_func tool to save the function.\n"
    "   c) Use the exec_generated_func tool to apply the function to the data frame.\n"
    # "   d) If the generated code executes successfully, run the save_successful_code tool.\n"

)

# Coding Instructions / Guidelines / Constraints
CODE_INST = (
    "When writing new Python functions, follow these guidelines:\n"
    "- Ensure the function is Pythonic, efficient, and handles edge cases.\n"
    "- Be sure that all expected arguments in the function already exist in the task.\n"
    "- WARNING EXAMPLE: Functions cannot be applied to a specific column (argument) if there are no columns listed in the task.\n"
    "- Include inline comments explaining the logic and any assumptions.\n"
    "- Test the function with realistic inputs to ensure correctness.\n"
    "- Use descriptive variable names to make the code readable.\n"
    "- Avoid hardcoding values; make the function reusable when possible.\n"
    "- Structure the code logically, with clear input and output specifications.\n"
    "- Employ textblob when handling spelling errors.\n"
)
#JESSE 1/21/25
# CURRENTLY NOT ACTIVE - IDEA THAT WE MIGHT NEED AT SOME POINT
CODE_INST_TROUBLESHOOTING = (
    "When LLM ENCOUNTERS ERRORS running the code on the first attempt...\n"
    "This can serve as a trouble shooting guide\n"
)


#=============================================================================================#
#                                      Util Functions                                         #
#=============================================================================================#

def print_stream(stream):
    for s in stream:
        message = s["messages"][-1]
        if isinstance(message, tuple):
            print(message)
        else:
            message.pretty_print()
